name: Publish Docker Image

on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: MinecraftChromeDev/ubuntunovncgitpoddocker
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        workdir: dockerfiles
        registry: ghcr.io
